"""autogenerated by genpy from wifi_lookup/WifiData.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import wifi_lookup.msg

class WifiData(genpy.Message):
  _md5sum = "a389391568f546e8de0a32553512a637"
  _type = "wifi_lookup/WifiData"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """StrArr[] HotSpots

================================================================================
MSG: wifi_lookup/StrArr
string MAC
string dB

"""
  __slots__ = ['HotSpots']
  _slot_types = ['wifi_lookup/StrArr[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       HotSpots

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(WifiData, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.HotSpots is None:
        self.HotSpots = []
    else:
      self.HotSpots = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.HotSpots)
      buff.write(_struct_I.pack(length))
      for val1 in self.HotSpots:
        _x = val1.MAC
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1.dB
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.HotSpots is None:
        self.HotSpots = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.HotSpots = []
      for i in range(0, length):
        val1 = wifi_lookup.msg.StrArr()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.MAC = str[start:end].decode('utf-8')
        else:
          val1.MAC = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.dB = str[start:end].decode('utf-8')
        else:
          val1.dB = str[start:end]
        self.HotSpots.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.HotSpots)
      buff.write(_struct_I.pack(length))
      for val1 in self.HotSpots:
        _x = val1.MAC
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1.dB
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.HotSpots is None:
        self.HotSpots = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.HotSpots = []
      for i in range(0, length):
        val1 = wifi_lookup.msg.StrArr()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.MAC = str[start:end].decode('utf-8')
        else:
          val1.MAC = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.dB = str[start:end].decode('utf-8')
        else:
          val1.dB = str[start:end]
        self.HotSpots.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
